build: false

environment:
  global:
    BINSTAR_USER: menpo
    BINSTAR_KEY:
      secure: mw1Fz5a5C0lT4CXzsOCADoo/Xa9YymZI3yjVZNR8f5GwYrVAOC2YXxyEG6NaSWZY
    PYTHON_VERSION: 2.7
#  matrix:
#    - PYTHON_VERSION: 2.7
#    - PYTHON_VERSION: 3.4
#
#
matrix:
   fast_finish: true
#  allow_failures:
#    - platform: x86
#      PYTHON_VERSION: 3.4
#    - platform: x64
#      PYTHON_VERSION: 3.4

platform:
- x86
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/jabooth/condaci/v0.2.1/condaci.py' C:\\condaci.py; echo "Done"
- cmd: python C:\\condaci.py setup %PYTHON_VERSION% --channel %BINSTAR_USER%
- cmd: C:\\Miniconda\\Scripts\\conda config --add channels %BINSTAR_USER%/channel/master

install:
- cmd: C:\\Miniconda\\python C:\\condaci.py auto ./conda --binstaruser %BINSTAR_USER% --binstarkey %BINSTAR_KEY%

notifications:
  - provider: Slack
    auth_token:
      secure: Jyd2NTPkBrrwBnl1C0mkNp5sUPGXzKrDgpZVDvPj72OUJtovXsO3795UsvktLucG
    channel: general
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false
